image: docker:latest

services:
  - docker:dind
  
variables:
  REGISTRY: docker.llmv.io
  PROJECTGROUP: android
  PROJECTNAME: lalamove-android-docker
  NEWTAG: 'latest'
  TAG: 'latest'

stages:
  - build

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker build -t $REGISTRY/$PROJECTGROUP/$PROJECTNAME:$TAG .
    - NEWTAG=$(eval docker run $REGISTRY/$PROJECTGROUP/$PROJECTNAME:$TAG)
    - docker tag $REGISTRY/$PROJECTGROUP/$PROJECTNAME:$TAG $REGISTRY/$PROJECTGROUP/$PROJECTNAME:$NEWTAG
    - docker push $REGISTRY/$PROJECTGROUP/$PROJECTNAME:$NEWTAG
  only:
    - master
  tags:
    - k8s
